theme: jekyll-theme-slate
name: Newup Consulting

description: Custom software that streamlines your business

author: Bob Crowley

author_email: bob@contrivedexample.com

url: http://newup.consulting

